<?php

/**
 * @file
 * Contains getfarmcredit_client.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function getfarmcredit_client_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the getfarmcredit_client module.
    case 'help.page.getfarmcredit_client':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Client module for GetFarmCredit locations provider.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function getfarmcredit_client_theme() {
  return [
    'getfarmcredit_client_map'     => [
      'variables' => [
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function getfarmcredit_client_page_attachments(array &$page) {
  $current_url = Url::fromRoute('<current>');
  if ($current_url->toString()=="/locations"){
    $base_url = \Drupal::request()->getSchemeAndHttpHost();
    $canonical = [
      '#tag' => 'meta',
      '#attributes' => [
        'rel' => 'canonical',
        'href' => $base_url . '/locations',
      ],
    ];
    $page['#attached']['html_head'][] = [$canonical, 'canonical'];
  }
}